kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock

volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock
