logging:
  level:
    io.evert: DEBUG
    web: INFO
server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      buffered: false
      suffix:
      file-date-format:

branch_deployer:

  root_clone_directory: /tmp/branch_deployer
  digital_ocean_auth_token: DO_TOKEN
  projects:
    - name: PROJECT_NAME
      webhookSecret: SECRET
      username: username
      password: password

